options:
  sleep_time: 1 #in hour

paths:
  baseDir: /dont_touch_this/solexa_runs/
  outputDir: /scratch/local/nanopore_data/
  groupDir: /data/
  external_groupDir: /scratch/local/external_nanopore_data/
  logDir:
  deepseq_qc: /rapidus/data/SAMBA/seq_share/01_Parkour/Sequence\ Quality/

parkour:
  url: https://parkour.ie-freiburg.mpg.de/api/analysis_list/analysis_list/
  user: stats@ie-freiburg.mpg.de
  password: (tJAk>p'UM<'\y9~

guppy_basecaller:
#base_calling_cmd =/package/guppy-3.4.3/bin/guppy_basecaller
  base_calling_cmd: /data/processing1/leily/guppy-5.0.7/ont-guppy/bin/guppy_basecaller
  base_calling_options: --recursive --compress_fastq --device cuda:0 --num_callers 10 --chunk_size 500 --chunks_per_runner 768 --gpu_runners_per_device 8
# guppy benchmark: https://esr-nz.github.io/gpu_basecalling_testing/gpu_benchmarking.html
  base_calling_barcode_options: --trim_barcodes --num_barcode_threads 10
  base_calling_RNA_options: --reverse_sequence true --u_substitution true --trim_strategy rna
  dna_model: /data/processing1/leily/guppy-5.0.7/ont-guppy/data/dna_r9.4.1_450bps_sup.cfg
  rna_model: /data/processing1/leily/guppy-5.0.7/ont-guppy/data/rna_r9.4.1_70bps_hac.cfg

flowcell:
  compatible_flowcells: FLO-MIN106
  compatible_kits:  [SQK-PCS109,SQK-RNA002,SQK-RNA003,SQK-PCB109,SQK-LSK109,SQK-RAD004]
  compatible_kits_with_barcoding: SQK-PCB109

mapping:
  index_options: -t 5 -K 20M -x map-ont -d
  mapping_cmd: /package/anaconda3/envs/minimap2-2.17/bin/minimap2
  mapping_dna_options: -t 2 -K 10M -ax map-ont -L
  mapping_rna_options: -t 4 -K 10M -ax splice -L -u f
  samtools_cmd: /package/anaconda3/envs/samtools-1.10/bin/samtools
  samtools_options: -@ 4
  bedtools_cmd: /package/anaconda3/envs/bedtools2-2.27.0/bin/bedtools
  bedtools_option: -s -split -name

nanocomp:
  qc_cmd: /package/anaconda3/envs/nanocomp-1.1.0/bin/NanoComp
  qc_options: -t 20 --names

pycoQc:
  barcodeSplit: /package/anaconda3/envs/pycoqc-2.5.0.23/bin/Barcode_split -u -v -f
  pycoQc: /package/anaconda3/envs/pycoqc-2.5.0.23/bin/pycoQC --summary_file

genome:
  dm6: /data/repository/organisms/dm6_ensembl/genome_fasta/genome.fa
  mouse: /data/repository/organisms/GRCm38_ensembl/genome_fasta/genome.fa #mm10
  hg38: /data/repository/organisms/GRCh38_ensembl/genome_fasta/genome.fa
  lambdaPhage: /data/repository/fastq_screen/LambdaPhage/genome.fa
  human_rRNA: /data/manke/group/ryan/rRNA/human_rRNA.fa
  mouse_rRNA: /data/manke/group/ryan/rRNA/mouse_rRNA.fa

transcripts:
  dm6:  /data/repository/organisms/dm6_ensembl/ensembl/release-93/genes.bed
  mouse: /data/repository/organisms/GRCm38_ensembl/ensembl/release-91/genes.bed #mm10
  hg38: /data/repository/organisms/GRCh38_ensembl/ensembl/release-91/genes.bed

contamination_report:
human_genome: /data/repository/organisms/GRCh38_ensembl/genome_fasta/genome.fa
human_rRNA: /data/manke/group/ryan/rRNA/human_rRNA.fa
mouse_genome: /data/repository/organisms/GRCm38_ensembl/genome_fasta/genome.fa
mouse_rRNA: /data/manke/group/ryan/rRNA/mouse_rRNA.fa
