options:
  sleep_time: 1 #in hour

paths:
  baseDir: /path/to/ont/files
  outputDir: /path/to/trnasfer/input/
  groupDir: /root/to/transfer
  external_groupDir: /root/to/transfer/external/
  logDir:
  deepseq_qc: /path/to/deepseq/qc/

parkour:
  url: parkour/api/url
  user: account
  password: password

guppy_basecaller:
  base_calling_cmd: path/to/guppy_basecaller
  base_calling_options: --recursive --compress_fastq --device cuda:0 --num_callers 10 --chunk_size 500 --chunks_per_runner 768 --gpu_runners_per_device 8
# guppy benchmark: https://esr-nz.github.io/gpu_basecalling_testing/gpu_benchmarking.html
  base_calling_barcode_options: --trim_barcodes --num_barcode_threads 10
  base_calling_RNA_options: --reverse_sequence true --u_substitution true --trim_strategy rna
  dna_model: /path/to/guppy/dna/model.cfg #hac
  rna_model: /path/to/guppy/rna/model.cfg

flowcell:
  compatible_flowcells: FLO-MIN106
  compatible_kits:  [SQK-PCS109,SQK-RNA002,SQK-RNA003,SQK-PCB109,SQK-LSK109,SQK-RAD004]
  compatible_kits_with_barcoding: SQK-PCB109

mapping:
  index_options: -t 5 -K 20M -x map-ont -d
  mapping_cmd: path/to/minimap2
  mapping_dna_options: -t 2 -K 10M -ax map-ont -L
  mapping_rna_options: -t 4 -K 10M -ax splice -L -u f
  samtools_cmd: /path/to/samtools
  samtools_options: -@ 4
  bedtools_cmd: /path/to/bedtools
  bedtools_option: -s -split -name

nanocomp:
  qc_cmd: /path/to/NanoComp
  qc_options: -t 20 --names

pycoQc:
  barcodeSplit: /path/to/pycoqc/Barcode_split -u -v -f
  pycoQc: /path/to/pycoqc/bin/pycoQC --summary_file

genome:
  drosophila: /path/to/genome.fa
  mouse: /path/to/genome.fa #mm10
  hg38: /path/to/genome.fa
  lambdaPhage: /path/to/genome.fa
  human_rRNA: /path/to/human_rRNA.fa
  mouse_rRNA: /path/to/mouse_rRNA.fa

transcripts:
  drosophila: /path/to/genes.bed
  mouse: /path/to/genes.bed #mm10
  hg38: /path/to/genes.bed

contamination_report:
human_genome: /path/to/genome.fa
human_rRNA: /path/to/human_rRNA.fa
mouse_genome: /path/to/genome.fa
mouse_rRNA: /path/to/mouse_rRNA.fa

email:
  from: a@host
  to: c@host
  host: mail.host
